#!/bin/sh
RESET="\033[0m"
echo "$ON_CYAN$RED   #####    $RESET"
echo "$ON_CYAN$RED  ######### $RESET"
echo "$ON_CYAN$GREEN  ###$YELLOW##$GREEN#$YELLOW#   $RESET"
echo "$ON_CYAN$GREEN #$YELLOW#$GREEN#$YELLOW###$GREEN#$YELLOW### $RESET"
echo "$ON_CYAN$GREEN #$YELLOW#$GREEN##$YELLOW###$GREEN#$YELLOW###$RESET"
echo "$ON_CYAN$GREEN ##$YELLOW####$GREEN#### $RESET"
echo "$ON_CYAN$YELLOW   #######  $RESET"
echo "$ON_CYAN$GREEN  ##$RED#$GREEN###    $RESET"
echo "$ON_CYAN$GREEN ###$RED#$GREEN##$RED#$GREEN### $RESET"
echo "$ON_CYAN$GREEN####$RED####$GREEN####$RESET"
echo "$ON_CYAN$YELLOW##$GREEN#$RED#$YELLOW#$RED##$YELLOW#$RED#$GREEN#$YELLOW##$RESET"
echo "$ON_CYAN$YELLOW###$RED######$YELLOW###$RESET"
echo "$ON_CYAN$YELLOW##$RED########$YELLOW##$RESET"
echo "$ON_CYAN$RED  ###  ###  $RESET"
echo "$ON_CYAN$GREEN ###    ### $RESET"
echo "$ON_CYAN$GREEN####    ####$RESET"
